frontend:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./conf.d:/etc/nginx/conf.d
    - ./logs:/var/log/nginx
    - ./ssl/letsencrypt:/etc/letsencrypt
    - ./placeholder:/usr/share/nginx/html